### ISSUE TITLE
includes and requires in the module broken

### ISSUE THREAD

**Issue by Shardj** [zf1s/zend-application#1]
Continuing from discussion [here](https://github.com/zf1s/zend-config/pull/1#issuecomment-453588385)

zend-application/library/Zend/Application/Resource/Modules.php line 78
zend-application/library/Zend/Controller/Dispatcher/Standard.php line 357
zend-validate/library/Zend/Validate/Hostname.php line 1780
zend-controller/library/Zend/Controller/Dispatcher/Standard.php line 357
zend-translate/library/Zend/Translate/Adapter/Array.php line 55
zend-view/library/Zend/View.php line 155 and 157
zend-http/library/Zend/Http/UserAgent/AbstractDevice.php line 787
zend-db/library/Zend/Db/Profiler/Firebug.php line 99

Maybe zend-cache/library/Zend/Cache.php on 148 and 190 as they refer to using include paths

**Comment by falkenhawk** [comment]
@Shardj 1.13 incoming with sorted out autoloader incompatibilities

**Comment by Shardj** [comment]
Thanks, I'm probably going to stick with my current repo though. It's proving popular and I don't want to have to spend time going and figuring out how to swap the projects out in my application.
